### ISSUE TITLE
Замечания по 2 лабе

### ISSUE THREAD

**Issue by nightnoryu** [ShiraseAkira/ATaFL#1]
## Правильность

Все ОК.

## Алгоритм

Все ОК.

## Код

1. Закомментированный код не стоит оставлять

https://github.com/ShiraseAkira/ATaFL/blob/cd9d0b391d09fa5eda0d0755fa4773f064abdff1/lab2/lab2.py#L135

2. Магические значения (типа `s` и `/`) лучше вынести в константы
3. Если еще вынести повторяющийся код из функций минимизации, то будет вообще конфетка

**Comment by ShiraseAkira** [comment]
1. Выкинул. Хотя думал, что никакого закомменченного кода и так не оставил.
2. Сделал
3. Сделал по большей части
